# Generated by Django 3.2.22 on 2024-01-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ITEM_CODE', models.CharField(max_length=50)),
                ('ITEM_NAME', models.CharField(max_length=255)),
                ('ITEM_IG_CODE', models.CharField(max_length=50)),
                ('ITEM_UOM_CODE', models.CharField(max_length=50)),
                ('ITEM_STK_NONSTK', models.CharField(max_length=10)),
                ('CLASSIFICATION', models.CharField(max_length=50)),
                ('PRODUCT_TYPE', models.CharField(max_length=50)),
                ('BRAND', models.CharField(max_length=50)),
                ('BRAND_CODE2', models.CharField(max_length=50)),
                ('CATEGORY', models.CharField(max_length=50)),
                ('SPECIFICATION', models.CharField(max_length=255)),
                ('SECTION_WIDTH', models.CharField(max_length=10)),
                ('PROFILE', models.CharField(max_length=10)),
                ('RIM_SIZE', models.CharField(max_length=10)),
                ('PATTERN', models.CharField(max_length=50)),
                ('PLAY_RATING', models.CharField(max_length=10)),
                ('OTHER', models.CharField(max_length=255)),
                ('VAT', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
